### ISSUE TITLE
Request: Add back the Factions integration

### ISSUE THREAD

**Issue by SmallSansSerif** [pmdevita/CreeperHeal2#11]
Can you have a check for faction territory like the old CreeperHeal? Specifically looking for [FactionsUUID](https://github.com/drtshock/Factions) support.

This was in the advanced.yml of the worlds

```
# Advanced world-specific settings
#
# restrict: Prevent replacement of some blocks. If use-whitelist is true, then
# only the blocks listed in the whitelist are replaced, otherwise every block
# except those listed in the blacklist are replaced. Entries are Material names.
# Values are separated by commas.
#
# replace-grass-with-dirt: If true, then grass blocks that are blown up will be
# replaced by plain dirt blocks.
#
# repair-time-of-day: Minecraft time at which every explosion and burnt block
# should be replaced. (-1 to deactivate)
# Sunrise is around 23000, noon 6000, sunset 13000, and midnight 18000. Day
# (zombies burning) starts at 0.
#
# protected-list: List of block types to protect (in the same format as the
# restrict lists).
#
# factions: To use with the Factions plugin. If the settings are set to true,
# the explosions in wilderness or territory are ignored by CreeperHeal (blocks
# are destroyed normally).
#

restrict:
  use-whitelist: false
  blacklist: 'AIR'
  whitelist: 'AIR'
replace-grass-with-dirt: false
repair-time-of-day: -1
protected-list: 'AIR'
factions:
  ignore-wilderness: false
  ignore-territory: true
```
